const words = {
  easy: {
    4: [
      "book",
      "tree",
      "fish",
      "bird",
      "moon",
      "star",
      "milk",
      "cake",
      "ship",
      "road",
    ],
    5: [
      "apple",
      "table",
      "chair",
      "plant",
      "bread",
      "light",
      "water",
      "smile",
      "stone",
      "sweet",
    ],
    6: [
      "banana",
      "orange",
      "grapes",
      "tomato",
      "potato",
      "butter",
      "cheese",
      "flower",
      "little",
      "silver",
    ],
  },

  medium: {
    4: [
      "lion",
      "wolf",
      "bear",
      "frog",
      "deer",
      "hawk",
      "seal",
      "goat",
      "crow",
      "swan",
    ],
    5: [
      "river",
      "mount",
      "ocean",
      "forest",
      "cloud",
      "storm",
      "flame",
      "earth",
      "stone",
      "field",
    ],
    6: [
      "desert",
      "island",
      "jungle",
      "valley",
      "canyon",
      "stream",
      "glacier",
      "meadow",
      "forest",
      "tundra",
    ],
  },

  hard: {
    4: [
      "axle",
      "yarn",
      "zest",
      "lynx",
      "wisp",
      "glyph",
      "omen",
      "rune",
      "veil",
      "saga",
    ],
    5: [
      "crypt",
      "glyph",
      "nymph",
      "quark",
      "vigor",
      "wrath",
      "zonal",
      "axiom",
      "blitz",
      "charm",
    ],
    6: [
      "zephyr",
      "quartz",
      "xenon",
      "voyage",
      "rhythm",
      "oxygen",
      "matrix",
      "cipher",
      "vertex",
      "cosmos",
    ],
  },
};

export function getRandomWord(difficulty, len) {
  const wordList = words[difficulty][len];
  const randomIndex = Math.floor(Math.random() * wordList.length);
  return wordList[randomIndex];
}
